### ISSUE TITLE
cannot find 'config.json'

### ISSUE THREAD

**Issue by YangWang92** [RF5/lmao#10]
Hi, 
Thanks for sharing such an interesting project!

However, I got an error when I deployed a local server.

![image](https://user-images.githubusercontent.com/3883941/135709390-4af36e72-5e7c-4552-9544-b742f877498c.png)

Did I miss something?

**Comment by RF5** [comment]
My apologies, the current code is configured for when the server is run on AWS with a special api key. To run locally, you should safely be able to comment out those `fetch` lines and the `setAPI` function. 

After commenting that out, hard code `_api_key` to whatever you use in django. If you aren't using any special API key checking in your local django server, just set it to empty `let api_key = "";` I think should work.
