### ISSUE TITLE
Could not establish connection

### ISSUE THREAD

**Issue by JustSaX** [RF5/lmao#11]
Hi

Super interesting project! I just tried to make it work local but I run into the following error message in Chrome dev tools console:

`Unchecked runtime.lastError: Could not establish connection. Receiving end does not exist.`

**Comment by RF5** [comment]
Hmm, is your django server backend also up and running? This error looks like it is struggling to find the inference backend.

**Comment by JustSaX** [comment]
Thanks for replying.

Yes Django is up and running and has the same address as in js source code.

**Comment by RF5** [comment]
Hmm, I am not too sure what might be the problem then. Did you install the extension directly from this repository, or from the chrome web store? If you manually loaded it by downloading this repository, you will need to update the [`editorExtensionId` in the `injector.js`](https://github.com/RF5/lmao/blob/master/lmao_integrator/injector.js#L6) file to match the one your browser has assigned to the extension. 

If that doesn't yield results, I am not too sure what else might be causing the issue, perhaps overleaf might have changed their website structuring that has caused this extension to no longer work...

**Comment by RF5** [comment]
Closing since the issue seems dead. Feel free to open again if you are still having problems.

**Comment by JustSaX** [comment]
Succesfully solved my problem. Thanks!
